spring:
  datasource:
    url: ${DB_URL_PROD}
    username: ${DATABASE_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
  jpa:
    hibernate:
      ddl-auto: update

application:
  secret_key: ${SECRET_KEY}
  file:
    upload-path: ${FILE_UPLOAD_PATH}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
        health:
          show-details: never
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true