spring:
  datasource:
    url: ${DB_URL_DEV}
    username: ${DATABASE_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: ${MONGO_DB_DATABASE}

application:
  secret_key: ${SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
        health:
          show-details: always
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true