spring:
  datasource:
    url: ${DB_URL_PROD}
    username: ${DATABASE_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: ${MONGO_DB_URI}

application:
  secret_key: ${SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
        health:
          show-details: never
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true