spring:
  datasource:
    url: ${DB_URL_PROD}
    username: ${DATABASE_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
  jpa:
    hibernate:
      ddl-auto: update

application:
  secret_key: ${SECRET_KEY}